#!/bin/bash

set -e

mkdir ~/.kube
mkdir -p /tmp/aws
cp .kube/config ~/.kube/config
cp .kube/resources/cluster_name.csv /tmp/aws/cluster_name.csv
cp .kube/resources/id.csv /tmp/aws/id.csv

ls /tmp/aws

path=$(pwd)
echo '#### AWS CONFIG ####'
mkdir -p ~/.aws
cp $AWS_CREDS ~/.aws/credentials
ls ~/.aws/
sudo bash -c "aws configure list"
git clone https://github.com/mayadata-io/litmus.git
cd litmus/k8s/aws/k8s-installer

# Deleting Pre-requiste
ansible-playbook delete-aws-cluster.yml -vv --extra-vars "region=eu-central-1 zone=eu-central-1a"