#!/bin/bash

set -e

mkdir ~/.kube
mkdir -p /tmp/aws
cp .kube/config ~/.kube/config

ls /tmp/aws

path=$(pwd)
echo '#### AWS CONFIG ####'
mkdir -p ~/.aws
cp $AWS_CREDS ~/.aws/credentials
sed 's|region = eu-central-1|region = us-west-2|' -i ~/.aws/config

git clone https://github.com/mayadata-io/litmus.git
cd litmus/k8s/aws/k8s-installer

vpcid=`cat /tmp/aws/id.csv | cut -d ',' -f1 | sed -r 's|vpc_id:||'`
echo $vpcid

echo '#### Delete subnets ####'
for i in `aws ec2 describe-subnets --filters Name=vpc-id,Values="${vpcid}" | grep subnet- | sed -E 's/^.*(subnet-[a-z0-9]+).*$/\1/'`; do aws ec2 delete-subnet --subnet-id=$i; done

echo '#### Detach internet gateways ####'
for i in `aws ec2 describe-internet-gateways --filters Name=attachment.vpc-id,Values="${vpcid}" | grep igw- | sed -E 's/^.*(igw-[a-z0-9]+).*$/\1/'`; do aws ec2 detach-internet-gateway --internet-gateway-id=$i --vpc-id=vpc-3279eb57; done

echo '#### Delete internet gateways ####'
for i in `aws ec2 describe-internet-gateways --filters Name=attachment.vpc-id,Values="${vpcid}" | grep igw- | sed -E 's/^.*(igw-[a-z0-9]+).*$/\1/'`; do aws ec2 delete-internet-gateway --internet-gateway-id=$i; done

echo '#### Delete the VPC ####'
aws ec2 delete-vpc --vpc-id ${vpcid}