#!/bin/bash
set -e
path=$(pwd)
mkdir -p ~/.kube
mkdir -p /tmp/aws
cp .kube/config ~/.kube/config
cp .kube/$CLUSTER ~/.kube/$CLUSTER 2>/dev/null || :
ls .kube

bash utils/pooling jobname:e2e-metrics
bash utils/e2e-cr jobname:$CLUSTER-cleanup jobphase:Running

echo '#### AWS CONFIG ####'
mkdir -p ~/.aws
cp $AWS_CREDS ~/.aws/credentials
sed 's|region = eu-central-1|region = us-west-2|' -i ~/.aws/config

git clone https://github.com/mayadata-io/litmus.git
cd litmus/k8s/aws/k8s-installer

{
    ls ~/.kube
    # Fetch cluster1 name
    cluster=$(cat ~/.kube/$CLUSTER)

    echo '#### Delete $CLUSTER ####'
    kops delete cluster --name k8s-${cluster}.k8s.local --state=s3://k8s-bucket-${cluster} --yes
    sleep 10

    if [[ "$CLUSTER" == cluster1 ]];then 
        aws s3 rm s3://k8s-bucket-${cluster} --recursive 
    fi
    
    aws s3api delete-bucket --bucket k8s-bucket-${cluster} --region us-west-2
    aws ec2 delete-tags --resources $RELEASE_SUBNET --tags Key=kubernetes.io/cluster/k8s-${cluster}.k8s.local
} || {
    echo '!!! Something went wrong during cluster cleanup !!!' 
}