#!/bin/bash
set -e
path=$(pwd)
mkdir -p ~/.kube
mkdir -p /tmp/aws

echo '#### AWS CONFIG ####'
mkdir -p ~/.aws
cp $AWS_CREDS ~/.aws/credentials
sed 's|region = us-west-2|region = eu-central-1|' -i ~/.aws/config

git clone https://github.com/mayadata-io/litmus.git
cd litmus/k8s/aws/k8s-installer

sed 's|region: eu-west-2|region: eu-central-1|' -i ./vars.yml
sed 's|zone: eu-west-2a|zone: eu-central-1a|' -i ./vars.yml
sed '$a\vpc_id: '"$DEV_VPC" -i ./vars.yml
sed '$a\subnet_id: '"$DEV_SUBNET" -i ./vars.yml

# Create k8s cluster
echo -e "\n************************ Create cluster *********************************************\n"
ansible-playbook create-aws-cluster.yml -vv --extra-vars "k8s_version=1.16.9 image=ami-03d8059563982d7b0"

CNAME=`cat /tmp/aws/cluster_name.csv | cut -d ',' -f1 | sed -r 's|cluster_name:||'`
mkdir -p $path/.kube
touch $path/.kube/$CLUSTER
echo $CNAME > $path/.kube/$CLUSTER

mkdir -p $path/.aws$CLUSTER
cat ~/.kube/config > $path/.aws$CLUSTER/config
cat ~/.kube/config > $path/.aws$CLUSTER/admin.conf

kubectl get nodes

echo -e "\n[ Print 'k8s version' ] ---------------------------------------------\n"
version=$(kubectl get nodes -o=jsonpath='{.items[0].status.nodeInfo.kubeletVersion}')
echo -e "KubernetesVersion: $version"

echo -e "\n"
