#!/bin/bash

set -ex

######################
##   Prerequisites  ##
######################

path=$(pwd)
# Copy kubeconfig
mkdir -p ~/.kube
cp  $path/.awscluster3/config ~/.kube/config

kubectl get po -n openebs

####################################
##  Sequencing and Running test   ##
####################################

bash utils/pooling jobname:tcid-dir-op-cstor-pool-recommend-list-mirror
bash utils/e2e-cr jobname:tcid-dir-op-cstor-pool-recommend-list-no-ndm jobphase:Running

# Cloning oep-e2e repository which contains all the test scripts
git clone https://$username:$password@github.com/mayadata-io/oep-e2e.git
cd oep-e2e
kubectl create -f litmus/director/TCID-DIR-OP-CSTOR-POOL-RECOMMEND-LIST-NO-NDM/run_litmus_test.yml
kubectl get pods -n litmus

test_name=list-recommendations-with-no-ndm
echo $test_name

## E2E Test case plan link
e2e_tc_plan_link=https://e2e.mayadata.io/docs/director/openebs-provisioning/TCID-DIR-OP-CSTOR-POOL-RECOMMEND-LIST-NO-NDM
echo -e "\nTest Plan Link: $e2e_tc_plan_link\n"

litmus_pod=$(kubectl get po -n litmus | grep $test_name  | awk {'print $1'} | tail -n 1)
echo $litmus_pod

job_status=$(kubectl get po  $litmus_pod -n litmus | awk {'print $3'} | tail -n 1)

while [[ "$job_status" != "Completed" ]]
do 
    job_status=$(kubectl get po  $litmus_pod -n litmus | awk {'print $3'} | tail -n 1)
    sleep 6
done
cd ..

kubectl logs -f $litmus_pod -n litmus
testResult=$(kubectl get litmusresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)
echo $testResult

if [ "$testResult" != Pass ]
then
  bash utils/e2e-cr jobname:tcid-dir-op-cstor-pool-recommend-list-no-ndm jobphase:Completed
  exit 1;
else
  bash utils/e2e-cr jobname:tcid-dir-op-cstor-pool-recommend-list-no-ndm jobphase:Completed
fi