#!/bin/bash

set -ex

######################
##   Prerequisites  ##
######################

path=$(pwd)
# Copy kubeconfig
mkdir -p ~/.kube
cp  $path/.awscluster3/config ~/.kube/config

kubectl get po -n openebs

####################################
##  Sequencing and Running test   ##
####################################

bash utils/pooling jobname:tcid-dir-op-install-openebs-dp-on-specific-node
bash utils/e2e-cr jobname:tcid-dir-op-re-install-openebs:Running


# Cloning oep-e2e repository which contains all the test scripts
git clone https://$username:$password@github.com/mayadata-io/oep-e2e.git

######################
##   Running test   ##
######################

kubectl create -f oep-e2e/litmus/director/TCID-DIR-OP-RE-INSTALL-OPENEBS/run_litmus_test.yml
kubectl get pods -n litmus
test_name=openebs-reinstallation
echo $test_name

## E2E Test case plan link
e2e_tc_plan_link=https://e2e.mayadata.io/docs/director/openebs-provisioning/TCID-DIR-OP-RE-INSTALL-OPENEBS
echo -e "\nTest Plan Link: $e2e_tc_plan_link\n"

litmus_pod=$(kubectl get po -n litmus | grep $test_name  | awk {'print $1'} | tail -n 1)
echo $litmus_pod
job_status=$(kubectl get po  $litmus_pod -n litmus | awk {'print $3'} | tail -n 1)
while [[ "$job_status" != "Completed" ]]
do 
    job_status=$(kubectl get po  $litmus_pod -n litmus | awk {'print $3'} | tail -n 1)
    sleep 6
done
kubectl logs -f $litmus_pod -n litmus
testResult=$(kubectl get litmusresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)
echo $testResult
if [ "$testResult" != Pass ]; then 
exit 1; 
else
    bash utils/e2e-cr jobname:tcid-dir-op-re-install-openebs jobphase:Completed
fi 