#!/bin/bash

set -ex

######################
##   Prerequisites  ##
######################

path=$(pwd)
# Copy kubeconfig
mkdir -p ~/.kube
cp  $path/.awscluster2/config ~/.kube/config

####################################
##  Sequencing and Running test   ##
####################################

bash utils/e2e-cr jobname:director-dmaas-sc-creation jobphase:Waiting
bash utils/e2e-cr jobname:director-dmaas-sc-creation jobphase:Running

kubectl apply -f $path/stages/14-director-gui-check/template/create-cstor-sc.yaml
kubectl get sc

# Create sc on cluster3
cp  $path/.awscluster3/config ~/.kube/config
kubectl apply -f $path/stages/14-director-gui-check/template/create-cstor-sc.yaml
kubectl get sc

# Create SPC on cluster
NODE=`kubectl get node --selector='!node-role.kubernetes.io/master' --no-headers | awk '{print $1}' | tail -n 1`
BLOCK_DEVICE=`kubectl get bd -n openebs -l kubernetes.io/hostname=${NODE} | grep Unclaimed | awk '{print $1}' | tail -n 1`
echo $BLOCK_DEVICE
sed -i "s/dummyvalue/${BLOCK_DEVICE}/g" $path/stages/14-director-gui-check/template/create-spc-pool.yaml
cat $path/stages/14-director-gui-check/template/create-spc-pool.yaml

kubectl create -f $path/stages/14-director-gui-check/template/create-spc-pool.yaml
kubectl create -f $path/stages/14-director-gui-check/template/create-spc-sc.yaml

kubectl get sc

cp  $path/.awscluster2/config ~/.kube/config
bash utils/e2e-cr jobname:director-dmaas-sc-creation jobphase:Completed