#!/bin/bash

set -ex

######################
##   Prerequisites  ##
######################

# Install minio on cluster 2
path=$(pwd)
# Copy kubeconfig
mkdir -p ~/.kube
cp  $path/.awscluster2/config ~/.kube/config

####################################
##  Sequencing and Running test   ##
####################################

bash utils/e2e-cr jobname:director-dmaas-sc-creation jobphase:Waiting
bash utils/e2e-cr jobname:director-dmaas-sc-creation jobphase:Running



kubectl apply -f $path/stages/14-director-gui-check/template/create-cstor-sc.yaml
kubectl get sc

# Install minio on cluster 3
cp  $path/.awscluster3/config ~/.kube/config
kubectl apply -f $path/stages/14-director-gui-check/template/create-cstor-sc.yaml
kubectl get sc

bash utils/e2e-cr jobname:director-dmaas-sc-creation jobphase:Completed