#!/bin/bash

set -ex


######################
##   Prerequisites  ##
######################

path=$(pwd)
# Copy kubeconfig
mkdir -p ~/.kube
cp  $path/.awscluster2/config ~/.kube/config
kubectl get ns

PV_CLAIM_NAME="minio-pv-claim-jiva-aws"
NAMESPACE="jiva-aws"
STORAGE_CLASS_NAME="openebs-jiva-default"
NODE_PORT="32756"

kubectl create ns ${NAMESPACE}

# git clone https://github.com/qiell/minio-manifest.git
mkdir -p $path/jiva-aws
cp -R $path/stages/14-director-gui-check/template/minio-manifest $path/jiva-aws

# Add pv claim name, namespace and storage class name in minio-pvc.yaml
sed 's|name: minio-pv-claim|name: '${PV_CLAIM_NAME}'|' -i $path/jiva-aws/minio-manifest/minio-pvc.yaml
sed 's|storageClassName: openebs-cstor-sparse|storageClassName: '${STORAGE_CLASS_NAME}'|' -i $path/jiva-aws/minio-manifest/minio-pvc.yaml
sed 's|namespace: test|namespace: '${NAMESPACE}'|' -i $path/jiva-aws/minio-manifest/minio-pvc.yaml

cat $path/jiva-aws/minio-manifest/minio-pvc.yaml

# Add pv claim name and namespace in minio-official.yaml
sed 's|namespace: test|namespace: '${NAMESPACE}'|' -i $path/jiva-aws/minio-manifest/minio-official.yaml
sed 's|claimName: minio-pv-claim|claimName: '${PV_CLAIM_NAME}'|' -i $path/jiva-aws/minio-manifest/minio-official.yaml

cat $path/jiva-aws/minio-manifest/minio-official.yaml

# Add node port and namespace in minio-official.yaml
sed 's|namespace: test|namespace: '${NAMESPACE}'|' -i $path/jiva-aws/minio-manifest/minio-svc.yaml
sed 's|nodePort: 32701|nodePort: '${NODE_PORT}'|' -i $path/jiva-aws/minio-manifest/minio-svc.yaml

cat $path/jiva-aws/minio-manifest/minio-svc.yaml

pwd
ls
kubectl get ns
kubectl apply -f $path/jiva-aws/minio-manifest/
kubectl get pod -n ${NAMESPACE}

####################################
##   Prerequisites GUI Automation ##
####################################
cp  .kube/config ~/.kube/config
cp .kube/url ~/.kube/url
URL=$(cat ~/.kube/url)
echo $URL

CI_PROJECT_NAME=$(echo $CI_PROJECT_NAME)
CI_PIPELINE_ID=$(echo $CI_PIPELINE_ID)
GUID=grid-${CI_PROJECT_NAME}-${CI_PIPELINE_ID}

echo '#### AWS CONFIG ####'
mkdir -p ~/.aws
cp $AWS_CREDS ~/.aws/credentials
sed 's|region = us-west-2|region = eu-north-1|' -i ~/.aws/config

output=`aws cloudformation describe-stacks --stack-name $GUID --query Stacks[].Outputs[].OutputValue | sed -r 's/"+//g'`
grid=`echo $output | awk {'print $2'}`


#copy aws and minio cred
mkdir -p ~/.dmaas
cp $AWS_CREDS ~/.dmaas/aws_cred
cp $MINIO_CREDS ~/.dmaas/minio_cred
#make empty directory
mkdir -p selenium-auto
cd selenium-auto
ls
# Cloning oep repository which contains all the test scripts
git clone https://$username:$password@github.com/mayadata-io/gui-automation.git
cd gui-automation

#creating credential file
cat ~/.dmaas/aws_cred ~/.dmaas/minio_cred >> cred.ini

######################
##   Running test  ##
######################
python3.7 -m pip install -r requirements.txt
#Running tests with gaau01 marker
python3.7 -m pytest -m dmaasJivaAws --url $URL --environment remote --hub $grid -v --tests-per-worker 10 --reruns 1 --html=./results/report.html
