#!/bin/bash

set -ex


######################
##   Prerequisites  ##
######################

path=$(pwd)
# Copy kubeconfig
mkdir -p ~/.kube
cp  $path/.awscluster2/config ~/.kube/config
kubectl get ns

PV_CLAIM_NAME="minio-pv-claim-device-aws"
NAMESPACE="device-aws"
STORAGE_CLASS_NAME="openebs-device"
NODE_PORT="32752"

kubectl create ns ${NAMESPACE}

# git clone https://github.com/qiell/minio-manifest.git
mkdir -p $path/device-aws
cp -R $path/stages/14-director-gui-check/template/minio-manifest $path/device-aws

kubectl get bd -n openebs | awk '{ if($4 == "Unclaimed"){print $2};}'
NODE_SELECTOR=`kubectl get bd -n openebs | awk '{ if($4 == "Unclaimed"){print $2};}' | awk 'NR==1'`
echo $NODE_SELECTOR

# Add pv claim name, namespace and storage class name in minio-pvc.yaml
sed 's|name: minio-pv-claim|name: '${PV_CLAIM_NAME}'|' -i $path/device-aws/minio-manifest/minio-pvc.yaml
sed 's|storageClassName: openebs-cstor-sparse|storageClassName: '${STORAGE_CLASS_NAME}'|' -i $path/device-aws/minio-manifest/minio-pvc.yaml
sed 's|namespace: test|namespace: '${NAMESPACE}'|' -i $path/device-aws/minio-manifest/minio-pvc.yaml

cat $path/device-aws/minio-manifest/minio-pvc.yaml

# Add pv claim name and namespace in minio-official.yaml
sed 's|namespace: test|namespace: '${NAMESPACE}'|' -i $path/device-aws/minio-manifest/minio-official.yaml
sed 's|claimName: minio-pv-claim|claimName: '${PV_CLAIM_NAME}'|' -i $path/device-aws/minio-manifest/minio-official.yaml
sed 's|kubernetes.io/os: linux|kubernetes.io/hostname: '${NODE_SELECTOR}'|' -i $path/device-aws/minio-manifest/minio-official.yaml
cat $path/device-aws/minio-manifest/minio-official.yaml

# Add node port and namespacein minio-svc.yaml
sed 's|namespace: test|namespace: '${NAMESPACE}'|' -i $path/device-aws/minio-manifest/minio-svc.yaml
sed 's|nodePort: 32701|nodePort: '${NODE_PORT}'|' -i $path/device-aws/minio-manifest/minio-svc.yaml


cat $path/device-aws/minio-manifest/minio-svc.yaml

pwd
ls
kubectl get ns
kubectl apply -f $path/device-aws/minio-manifest/
kubectl get pod -n ${NAMESPACE}

####################################
##   Prerequisites GUI Automation ##
####################################

cp  .kube/config ~/.kube/config
cp .kube/url ~/.kube/url
URL=$(cat ~/.kube/url)
echo $URL

CI_PROJECT_NAME=$(echo $CI_PROJECT_NAME)
CI_PIPELINE_ID=$(echo $CI_PIPELINE_ID)
GUID=grid-${CI_PROJECT_NAME}-${CI_PIPELINE_ID}

echo '#### AWS CONFIG ####'
mkdir -p ~/.aws
cp $AWS_CREDS ~/.aws/credentials
sed 's|region = us-west-2|region = eu-north-1|' -i ~/.aws/config

output=`aws cloudformation describe-stacks --stack-name $GUID --query Stacks[].Outputs[].OutputValue | sed -r 's/"+//g'`
grid=`echo $output | awk {'print $2'}`

# Cloning oep repository which contains all the test scripts
git clone https://$username:$password@github.com/mayadata-io/gui-automation.git
cd gui-automation

#creating credential file
cat $AWS_CREDS $MINIO_CREDS > cred.ini

######################
##   Running test  ##
######################
python3.7 -m pip install -r requirements.txt
#Running tests with gaau01 marker
python3.7 -m pytest -m dmaasDeviceAws --url $URL --environment remote --hub $grid -v --tests-per-worker 10 --reruns 1 --html=./results/report.html

#delete credential file
rm -rf cred.ini