#!/bin/bash
set -ex

######################
##   Prerequisites  ##
######################
mkdir ~/.kube
cp  .kube/config ~/.kube/config
cp .kube/url ~/.kube/url
URL=$(cat ~/.kube/url)
echo $URL

# Cloning oep repository which contains all the test scripts
git clone https://$username:$password@github.com/mayadata-io/gui-automation.git
cd gui-automation
######################
##   Running test  ##
######################
python3.7 -m pip install -r requirements.txt
#Running tests with cluster marker
python3.7 -m pytest -m gaal01 --url $URL --environment remote -v --tests-per-worker 10 --reruns 1 --html=./results/report.html