#!/bin/bash

set -ex


######################
##   Prerequisites  ##
######################

path=$(pwd)
# Copy kubeconfig
mkdir -p ~/.kube
cp  $path/.awscluster2/config ~/.kube/config

####################################
##  Sequencing and Running test   ##
####################################
bash utils/pooling jobname:tcid-dir-dmaas-schd-jiva-minio-bucket
bash utils/e2e-cr jobname:tcid-dir-dmaas-schd-local-hp-minio-bucket jobphase:Running

kubectl get ns

PV_CLAIM_NAME="minio-pv-claim-hostpath-minio"
NAMESPACE="hostpath-minio"
STORAGE_CLASS_NAME="openebs-hostpath"
NODE_PORT="32755"

kubectl create ns ${NAMESPACE}

# git clone https://github.com/qiell/minio-manifest.git
mkdir -p $path/hostpath-minio
cp -R $path/stages/14-director-gui-check/template/minio-manifest $path/hostpath-minio


# Add pv claim name, namespace and storage class name in minio-pvc.yaml
sed 's|name: minio-pv-claim|name: '${PV_CLAIM_NAME}'|' -i $path/hostpath-minio/minio-manifest/minio-pvc.yaml
sed 's|storageClassName: openebs-cstor-sparse|storageClassName: '${STORAGE_CLASS_NAME}'|' -i $path/hostpath-minio/minio-manifest/minio-pvc.yaml
sed 's|namespace: test|namespace: '${NAMESPACE}'|' -i $path/hostpath-minio/minio-manifest/minio-pvc.yaml

cat $path/hostpath-minio/minio-manifest/minio-pvc.yaml

# Add pv claim name and namespace in minio-official.yaml
sed 's|namespace: test|namespace: '${NAMESPACE}'|' -i $path/hostpath-minio/minio-manifest/minio-official.yaml
sed 's|claimName: minio-pv-claim|claimName: '${PV_CLAIM_NAME}'|' -i $path/hostpath-minio/minio-manifest/minio-official.yaml

cat $path/hostpath-minio/minio-manifest/minio-official.yaml

# Add node port and namespace in minio-official.yaml
sed 's|namespace: test|namespace: '${NAMESPACE}'|' -i $path/hostpath-minio/minio-manifest/minio-svc.yaml
sed 's|nodePort: 32701|nodePort: '${NODE_PORT}'|' -i $path/hostpath-minio/minio-manifest/minio-svc.yaml

cat $path/hostpath-minio/minio-manifest/minio-svc.yaml

pwd
ls
kubectl get ns
kubectl apply -f $path/hostpath-minio/minio-manifest/
kubectl get pod -n ${NAMESPACE}
kubectl get sc

####################################
##   Prerequisites GUI Automation ##
####################################

cp  .kube/config ~/.kube/config
cp .kube/url ~/.kube/url
URL=$(cat ~/.kube/url)
echo $URL

CI_PROJECT_NAME=$(echo $CI_PROJECT_NAME)
CI_PIPELINE_ID=$(echo $CI_PIPELINE_ID)
GUID=grid-${CI_PROJECT_NAME}-${CI_PIPELINE_ID}

#copy aws and minio cred
mkdir -p ~/.dmaas
cp $AWS_CREDS ~/.dmaas/aws_cred
cp $MINIO_CREDS ~/.dmaas/minio_cred
#make empty directory
mkdir -p selenium-auto
cd selenium-auto

# Cloning oep repository which contains all the test scripts
git clone https://$username:$password@github.com/mayadata-io/gui-automation.git
cd gui-automation

#creating credential file
cat ~/.dmaas/aws_cred ~/.dmaas/minio_cred >> cred.ini

bash scripts/dop-gui-stages/run-gui-tests.sh ${GROUP} ${GUID} ${URL} ${THREADS} eu-north-1

cp  $path/.awscluster2/config ~/.kube/config
cd ../..
bash utils/e2e-cr jobname:tcid-dir-dmaas-schd-local-hp-minio-bucket jobphase:Completed

# Delete minio application
kubectl delete -f $path/hostpath-minio/minio-manifest/