#!/bin/bash

set -ex


######################
##   Prerequisites  ##
######################

mkdir ~/.kube
cp  .kube/config ~/.kube/config
cp .kube/url ~/.kube/url
URL=$(cat ~/.kube/url)
echo $URL

path=$(pwd)
cp  $path/.awscluster2/config ~/.kube/config

####################################
##  Sequencing and Running test   ##
####################################
bash utils/pooling jobname:tcid-dir-dmaas-schd-local-dev-minio-bucket
bash utils/e2e-cr jobname:tcid-dir-dmaas-minio-delete jobphase:Running

CI_PROJECT_NAME=$(echo $CI_PROJECT_NAME)
CI_PIPELINE_ID=$(echo $CI_PIPELINE_ID)
GUID=grid-${CI_PROJECT_NAME}-${CI_PIPELINE_ID}

#make empty directory
mkdir -p selenium-auto
cd selenium-auto

# Cloning oep repository which contains all the test scripts
git clone https://$username:$password@github.com/mayadata-io/gui-automation.git
cd gui-automation

bash scripts/dop-gui-stages/run-gui-tests.sh ${GROUP} ${GUID} ${URL} ${THREADS} eu-north-1

#cp  $path/.awscluster2/config ~/.kube/config
cd ../..
bash utils/e2e-cr jobname:tcid-dir-dmaas-minio-delete jobphase:Completed