#!/bin/bash
set -e

path=$(pwd)
mkdir ~/.kube
cp .aws$CLUSTER/config ~/.kube/config

bash utils/pooling jobname:trrc01-$CLUSTER-connect-check
bash utils/e2e-cr jobname:client-$CLUSTER-components-check jobphase:Running

git clone https://$username:$password@github.com/mayadata-io/oep-e2e.git
echo "Check cluster client components-------------------------------------------------"
kubectl create -f oep-e2e/litmus/director/cluster-connect-check/run_litmus_test.yml
test_name=cluster-connect-check
echo $test_name
litmus_pod=$(kubectl get po -n litmus | grep $test_name  | awk {'print $1'} | tail -n 1)
echo $litmus_pod
job_status=$(kubectl get po  $litmus_pod -n litmus | awk {'print $3'} | tail -n 1)
while [[ "$job_status" != "Completed" ]]
do 
    job_status=$(kubectl get po  $litmus_pod -n litmus | awk {'print $3'} | tail -n 1)
    sleep 6
done
kubectl logs -f $litmus_pod -n litmus
testResult=$(kubectl get litmusresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)
echo $testResult
if [ "$testResult" != Pass ]
then 
    exit 1; 
else
    bash utils/e2e-cr jobname:client-$CLUSTER-components-check jobphase:Completed
fi

