#!/bin/bash
set -e

path=$(pwd)
mkdir ~/.kube
cp .aws$CLUSTER/config ~/.kube/config
cp .kube/secret.yaml ~/.kube/secret.yaml

sleep 100

bash utils/e2e-cr jobname:trrc01-$CLUSTER-connect-check jobphase:Running 

kubectl apply -f secret.yaml 
git clone https://$username:$password@github.com/mayadata-io/oep-e2e.git
echo "Connect new cluster -------------------------------------------------"
sed 's|value: oep-cluster|value: oep-cluster-'$CLUSTER'|' -i oep-e2e/litmus/director/cluster-connect/run_litmus_test.yml
kubectl create -f oep-e2e/litmus/director/cluster-connect/run_litmus_test.yml
test_name=cluster-connect
echo $test_name
litmus_pod=$(kubectl get po -n litmus | grep $test_name  | awk {'print $1'} | tail -n 1)
echo $litmus_pod
job_status=$(kubectl get po  $litmus_pod -n litmus | awk {'print $3'} | tail -n 1)
while [[ "$job_status" != "Completed" ]]
do 
    job_status=$(kubectl get po  $litmus_pod -n litmus | awk {'print $3'} | tail -n 1)
    sleep 6
done
kubectl logs -f $litmus_pod -n litmus
testResult=$(kubectl get litmusresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)
echo $testResult
if [ "$testResult" != Pass ]
then 
    exit 1; 
else
    bash utils/e2e-cr jobname:trrc01-$CLUSTER-connect-check jobphase:Completed
fi