#!/bin/bash
set -ex

######################
##   Prerequisites  ##
######################
mkdir -p ~/.kube
cp  .kube/config ~/.kube/config
cp .kube/url ~/.kube/url

# director url
URL=$(cat ~/.kube/url)
echo $URL

# Cloning oep-e2e repository which contains all the test scripts
git clone https://$username:$password@github.com/mayadata-io/oep-e2e.git
######################
##   Running test  ##
######################
test_name=cluster-connect-check
echo $test_name
kubectl get pods
kubectl create -f oep-e2e/litmus/director/cluster-connect-check/run_litmus_test.yml
# check litmus test result
litmus_pod=$(kubectl get po -n litmus | grep $test_name  | awk {'print $1'} | tail -n 1)
echo $litmus_pod
job_status=$(kubectl get po  $litmus_pod -n litmus | awk {'print $3'} | tail -n 1)
while [[ "$job_status" != "Completed" ]]
do 
    job_status=$(kubectl get po  $litmus_pod -n litmus | awk {'print $3'} | tail -n 1)
    sleep 6
done
kubectl logs -f $litmus_pod -n litmus
testResult=$(kubectl get litmusresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)
echo $testResult
if [ "$testResult" != Pass ]; then 
exit 1; 
fi
