#!/bin/bash

set -ex

######################
##   Prerequisites  ##
######################

path=$(pwd)
# Copy kubeconfig
mkdir -p ~/.kube
cp  $path/.awscluster3/config ~/.kube/config

kubectl get po -n openebs

####################################
##  Sequencing and Running test   ##
####################################

# Cloning oep-e2e repository which contains all the test scripts
git clone https://$username:$password@github.com/mayadata-io/oep-e2e.git
cd oep-e2e
kubectl create -f litmus/director/TCID-DIR-OP-OPENEBS-UPGRADE-CP/run_litmus_test.yml
kubectl get pods -n litmus

test_name=control-plane-upgrade
echo $test_name

## E2E Test case plan link
e2e_tc_plan_link=https://e2e.mayadata.io/docs/director/openebs-provisioning/TCID-DIR-OP-OPENEBS-UPGRADE-CP
echo -e "\nTC_E2E_PLAN_LINK: $e2e_tc_plan_link\n"

litmus_pod=$(kubectl get po -n litmus | grep $test_name  | awk {'print $1'} | tail -n 1)
echo $litmus_pod

job_status=$(kubectl get po  $litmus_pod -n litmus | awk {'print $3'} | tail -n 1)

while [[ "$job_status" != "Completed" ]]
do 
    job_status=$(kubectl get po  $litmus_pod -n litmus | awk {'print $3'} | tail -n 1)
    sleep 6
done
cd ..

kubectl logs -f $litmus_pod -n litmus
testResult=$(kubectl get litmusresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)
echo $testResult
