#!/bin/bash

set -e

path=$(pwd)
echo $path
echo '#### AWS CONFIG ####'
rm -f ~/.aws/credentials
echo $AWS_CREDS
echo $AWS_CREDS > ~/.aws/credentials
ls ~/.aws/
cat ~/.aws/credentials

sudo bash -c "aws configure list"
git clone https://github.com/mayadata-io/litmus.git
cd litmus/k8s/aws/k8s-installer

# set variables
job_id=$(echo CI_JOB_ID)
pipeline_id=$(echo CI_PIPELINE_ID)
commit_sha=$(echo CI_COMMIT_SHA)
# Create VPC
echo "CREATING VPC, Subnet, Internet-Gateway and route-table"
ansible-playbook pre-requisite.yml -vv --extra-vars "region=eu-central-1 zone=eu-central-1a"

# Create k8s cluster
echo "CREATING CLUSTER"
ansible-playbook create-aws-cluster.yml -vv --extra-vars "k8s_version=1.11.1 region=eu-central-1 zone=eu-central-1a image=ami-03d8059563982d7b0 cloud=aws networking=kubenet"
pwd
ls
mkdir $path/.kube
cat ~/.kube/config > $path/.kube/config
cat ~/.kube/config > $path/.kube/admin.conf

# Export VPC network name
SID=`cat /tmp/aws/id.csv | cut -d ',' -f3`
echo $SID

kubectl get nodes
wget https://raw.githubusercontent.com/openebs/litmus/master/hack/rbac.yaml
kubectl apply -f rbac.yaml
kubectl create clusterrolebinding default-admin --clusterrole cluster-admin --serviceaccount=default:default
kubectl create configmap kubeconfig --from-file=$path/.kube/admin.conf -n litmus

# Create firewall-rule
# aws ec2 authorize-security-group-ingress \
#     --group-id $SID \
#     --protocol tcp \
#     --port 30380 \
#     --cidr 0.0.0.0/0