#!/bin/bash

set -e

path=$(pwd)
echo $path
echo '#### AWS CONFIG ####'
mkdir -p ~/.aws
cp $AWS_CREDS ~/.aws/credentials
sed 's|region = eu-central-1|region = us-west-2|' -i ~/.aws/config
ls ~/.aws/

echo "VPC: $RELEASE_VPC"

sudo bash -c "aws configure list"
git clone https://github.com/mayadata-io/litmus.git
cd litmus/k8s/aws/k8s-installer

sed '$a\vpc_id: '"$RELEASE_VPC" -i ./vars.yml
sed '$a\subnet_id: '"$RELEASE_SUBNET" -i ./vars.yml

# Create k8s cluster
echo "CREATING CLUSTER"
ansible-playbook create-aws-cluster.yml -vv --extra-vars "k8s_version=1.15.10 image=ami-02d0ea44ae3fe9561 node_count=1 master_size=m5a.xlarge node_size=m5a.xlarge"

mkdir $path/.kube
mkdir $path/.kube/resources
cat ~/.kube/config > $path/.kube/config
cat ~/.kube/config > $path/.kube/admin.conf
cp -r /tmp/aws/* $path/.kube/resources
ls $path/.kube

# Export Cluster name
CNAME=`cat /tmp/aws/cluster_name.csv | cut -d ',' -f1 | sed -r 's|cluster_name:||'`

touch $path/.kube/cluster1
echo $CNAME > $path/.kube/cluster1

kubectl get nodes
wget https://raw.githubusercontent.com/openebs/litmus/master/hack/rbac.yaml
kubectl apply -f rbac.yaml
kubectl create clusterrolebinding default-admin --clusterrole cluster-admin --serviceaccount=default:default
kubectl create configmap kubeconfig --from-file=$path/.kube/admin.conf -n litmus

# Create firewall-rule
NGROUP=`aws ec2 describe-security-groups --filters Name=vpc-id,Values=$RELEASE_VPC Name=group-name,Values=nodes.k8s-$CNAME.k8s.local --query SecurityGroups[].GroupId`
NSIG=`echo $NGROUP | awk {'print $2'} | sed -r 's/"+//g'`
MGROUP=`aws ec2 describe-security-groups --filters Name=vpc-id,Values=$RELEASE_VPC Name=group-name,Values=masters.k8s-$CNAME.k8s.local --query SecurityGroups[].GroupId`
MSIG=`echo $MGROUP | awk {'print $2'} | sed -r 's/"+//g'`
aws ec2 authorize-security-group-ingress --group-id $NSIG --protocol all --port all --cidr 0.0.0.0/0
aws ec2 authorize-security-group-ingress --group-id $MSIG --protocol all --port all --cidr 0.0.0.0/0