#!/bin/bash

set -ex

job_id=$(echo $CI_JOB_ID)
job_name=$(echo $CI_JOB_NAME)
gittoken=$(echo "$github_token")
current_time=$(date)
branch_name=$CI_COMMIT_REF_NAME

######################
##   Prerequisites  ##
######################

path=$(pwd)
# Copy kubeconfig
mkdir -p ~/.kube
cp  $path/.awscluster/config ~/.kube/config
cp .kube/cluster2 ~/.kube/cluster2
cp .kube/cluster3 ~/.kube/cluster3

echo '#### AWS CONFIG ####'
mkdir -p ~/.aws
cp $AWS_CREDS ~/.aws/credentials
sed 's|region = eu-central-1|region = us-west-2|' -i ~/.aws/config

git clone https://github.com/mayadata-io/litmus.git
cd litmus/k8s/aws/ebs-volumes

sed 's|region: eu-west-2|region: us-west-2|' -i ./vars.yml
sed 's|zone: eu-west-2a|zone: us-west-2a|' -i ./vars.yml
sed 's|volume_size: 50|volume_size: 20|' -i ./vars.yml

ansible-playbook create-ebs-volume.yml -vv --extra-vars "cluster_name=nodes.${cluster2}"
ansible-playbook create-ebs-volume.yml -vv --extra-vars "cluster_name=nodes.${cluster2}"
ansible-playbook create-ebs-volume.yml -vv --extra-vars "cluster_name=nodes.${cluster2}"
ansible-playbook create-ebs-volume.yml -vv --extra-vars "cluster_name=nodes.${cluster3}"
ansible-playbook create-ebs-volume.yml -vv --extra-vars "cluster_name=nodes.${cluster3}"
ansible-playbook create-ebs-volume.yml -vv --extra-vars "cluster_name=nodes.${cluster3}"