#!/bin/bash
set -ex

job_id=$(echo $CI_JOB_ID)
job_name=$(echo $CI_JOB_NAME)
gittoken=$(echo "$github_token")
current_time=$(date)
branch_name=$CI_COMMIT_REF_NAME
COUNTER=0

######################
##   Prerequisites  ##
######################

path=$(pwd)
# Copy kubeconfig
mkdir -p ~/.kube
cp  $path/.aws$CLUSTER/config ~/.kube/config
cp .kube/$CLUSTER ~/.kube/$CLUSTER

echo '#### AWS CONFIG ####'
mkdir -p ~/.aws
cp $AWS_CREDS ~/.aws/credentials
sed 's|region = eu-central-1|region = us-west-2|' -i ~/.aws/config

kubectl get disks

cd stages/17-ebs-volume
ls

sed 's|region: eu-west-2|region: us-west-2|' -i ./vars.yml
sed 's|zone: eu-west-2a|zone: us-west-2a|' -i ./vars.yml
sed 's|volume_size: 50|volume_size: 20|' -i ./vars.yml
clustername=$(cat ~/.kube/$CLUSTER)
chars=( {f..p} )

while [  $COUNTER -lt "$NUMBEROFVOLUMES" ]; do
    chr="${chars[$COUNTER]}"

    ansible-playbook create-ebs-volume.yml -vv --extra-vars "cluster_name=nodes.k8s-$clustername.k8s.local device_name=/dev/sd$chr"
    let COUNTER=COUNTER+1
done

kubectl get disks