#!/bin/bash

set -e

path=$(pwd)
mkdir -p ~/.kube

CI_PROJECT_NAME=$(echo $CI_PROJECT_NAME)
CI_PIPELINE_ID=$(echo $CI_PIPELINE_ID)
GUID=grid-${CI_PROJECT_NAME}-${CI_PIPELINE_ID}

sleep 180

echo -e "\n************************ Configure Selenium Grid **********************************\n"
git clone https://$username:$password@github.com/mayadata-io/gui-automation.git
cd gui-automation/scripts/grid
cat selenium-grid-config.yml

bash configure-grid.sh ${GUID} eu-north-1
