#!/bin/bash

set -e

path=$(pwd)
mkdir -p ~/.kube
cp .kube/cluster1 ~/.kube/cluster1

echo '#### AWS CONFIG ####'
mkdir -p ~/.aws
cp $AWS_CREDS ~/.aws/credentials
sed 's|region = eu-central-1|region = eu-north-1|' -i ~/.aws/config

git clone https://$username:$password@github.com/mayadata-io/gui-automation.git
cd gui-automation
tests_count=`find . -type f -name '*_test.py' -exec grep -e 'def test_' '{}' \; | wc -l`
echo "Number of GUI test scripts: $tests_count"

git clone https://$username:$password@github.com/mayadata-io/oep-e2e-aws.git
cd oep-e2e-aws/stages/16-selenium-grid/templates
ls
cluster1=$(cat ~/.kube/cluster1)

aws cloudformation create-stack --stack-name selenium-grid-${cluster1} --template-body file://hub.yml --parameters ParameterKey=NumberOfChromeNodes,ParameterValue=$tests_count ParameterKey=ClusterName,ParameterValue=${cluster1} ParameterKey=LogName,ParameterValue=${cluster1}