#!/bin/bash

set -e

path=$(pwd)
rm -f /tmp/aws/cluster_name.csv
echo $path
echo '#### AWS CONFIG ####'
mkdir -p ~/.aws
cp $AWS_CREDS ~/.aws/credentials
ls ~/.aws/

aws cloudformation create-stack --stack-name selenium-grid --template-body file:///templates/hub.yml --parameters ParameterKey=NumberOfChromeNodes,ParameterValue=20