#!/bin/bash

set -e

path=$(pwd)
rm -f /tmp/aws/cluster_name.csv
echo $path
echo '#### AWS CONFIG ####'
mkdir -p ~/.aws
cp $AWS_CREDS ~/.aws/credentials
ls ~/.aws/

aws cloudformation delete-stack --stack-name selenium-grid