#!/bin/bash

set -e

path=$(pwd)
mkdir -p ~/.kube
cp .kube/cluster1 ~/.kube/cluster1
echo $path

echo '#### AWS CONFIG ####'
mkdir -p ~/.aws
cp $AWS_CREDS ~/.aws/credentials
sed 's|region = eu-central-1|region = eu-north-1|' -i ~/.aws/config
ls ~/.aws/
cluster1=$(cat ~/.kube/cluster1)

aws cloudformation delete-stack --stack-name selenium-grid-${cluster1}