#!/bin/bash
set -e

CI_PROJECT_NAME=$(echo $CI_PROJECT_NAME)
CI_PIPELINE_ID=$(echo $CI_PIPELINE_ID)
GUID=grid-${CI_PROJECT_NAME}-${CI_PIPELINE_ID}

path=$(pwd)
echo $path

echo '#### AWS CONFIG ####'
mkdir -p ~/.aws
cp $AWS_CREDS ~/.aws/credentials
sed 's|region = eu-central-1|region = eu-north-1|' -i ~/.aws/config

{
    aws cloudformation delete-stack --stack-name ${GUID}
} || {
    echo 'Selenium CloudFormation stack was absent'
}